#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)
host = data["host"]
h2hs = data.get("http2https", True)
agent.set_env("TRAEFIK_HOST", host)
agent.set_env("TRAEFIK_HTTP2HTTPS", h2hs)
agent.set_env("SMTP_FROM", data.get("from", ""))
agent.set_env("SMTP_TO", data.get("to", ""))
agent.set_env("SSH_USER", data.get("ssh_user", "audit-collector"))
agent.set_env("SCAN_INTERVAL_HOURS", data.get("scan_interval_hours", "4"))
agent.set_env("EXPIRE_WARN_DAYS", data.get("expire_warn_days", "7"))
agent.set_env("EXPIRE_WARN_DAYS_2", data.get("expire_warn_days_2", "2"))
agent.set_env("ADMIN_USERNAME", data.get("admin_username", "admin"))
agent.set_env("ADMIN_EMAIL", data.get("admin_email", "admin@example.com"))
agent.set_env("ADMIN_PASSWORD", data.get("admin_password", "admin"))
agent.set_env("TZ", data.get("tz", "UTC"))
agent.set_env("POSTGRES_DB", "ssh_manager")
agent.set_env("POSTGRES_USER", "ssh_manager")
secrets = agent.read_envfile("secrets.env")
agent.set_env("POSTGRES_PASSWORD", secrets["POSTGRES_PASSWORD"])
