#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)
host = data["host"]
h2hs = data.get("http2https", True)
agent.set_env("TRAEFIK_HOST", host)
agent.set_env("TRAEFIK_HTTP2HTTPS", h2hs)
agent.set_env("ADMIN_USERNAME", data.get("admin_username", "admin"))
agent.set_env("ADMIN_EMAIL", data.get("admin_email", "admin@example.com"))
agent.set_env("ADMIN_PASSWORD", data.get("admin_password", "admin"))
agent.set_env("POSTGRES_DB", "ssh_manager")
agent.set_env("POSTGRES_USER", "ssh_manager")
agent.set_env("SSH_USER", data.get("ssh_user", "audit-collector"))
