#
# Roundcube state/backup include patterns for Restic
# Syntax reference: https://pkg.go.dev/path/filepath#Glob
# Restic --files-from: https://restic.readthedocs.io/en/stable/040_backup.html#including-files
# List here what you want to save during backup : volumes or file Path


state/sam.pg_dump
state/secrets.env
state/collector_key
state/collector_key.pub
state/known_hosts
volumes/ssh_data
