#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent
import os

request = json.load(sys.stdin)
renv = request['environment']

configure_retval = agent.tasks.run(agent_id=os.environ['AGENT_ID'], action='configure-module', data={
    "host": renv["TRAEFIK_HOST"],
    "ssh_user": renv.get("SSH_USER", "audit-collector"),
    "admin_username": renv.get("ADMIN_USERNAME", "admin"),
    "admin_email": renv.get("ADMIN_EMAIL", "admin@example.com"),
    "admin_password": renv.get("ADMIN_PASSWORD", "admin"),
})
agent.assert_exp(configure_retval['exit_code'] == 0, "The configure-module subtask failed!")
